# Generated by Django 4.2.7 on 2023-12-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserType',
            field=models.CharField(blank=True, choices=[('User', 'User'), ('Instructor', 'Instructor')], default='user', max_length=15, null=True),
        ),
    ]
